CREATE TABLE APROVADORES_RH(
    ID_APROVADOR NUMBER(3) GENERATED ALWAYS AS IDENTITY NOT NULL,
    EMPRESA_DEPARTAMENTO_ID_EMPDEP VARCHAR(50) NOT NULL,
    GESTOR_DIRETO NUMBER(3) NOT NULL,
    APROVADOR_FILIAL NUMBER(3) NOT NULL,
    APROVADOR_AREA NUMBER(3) NOT NULL,
    APROVADOR_MARCA NUMBER(3) NOT NULL,
    APROVADOR_SUPERINTENTE NUMBER(3) NOT NULL,
    PRIMARY KEY(ID_APROVADOR)
);
